# Generated by Django 2.2.2 on 2019-06-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.TextField(max_length=20)),
                ('nro_doc', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=20)),
                ('departamento', models.CharField(max_length=150)),
                ('municipio', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombres_contacto', models.CharField(max_length=150)),
                ('apellidos_contacto', models.CharField(max_length=150)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('grupo_etnico', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_liderazgo', models.CharField(blank=True, max_length=100, null=True)),
                ('organizacion_pertenece', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
